### ISSUE TITLE
How set the site for real deploy?

### ISSUE THREAD

**Issue by vlafiser** [BradDenver/react-static-site#6]
Hi man, thank you for your time!

I'm trying deploy the site to the Heroku, because I want use your template for my personal website. But, the site not working for me on the Heroku server. All is right, but I mean the start script is not fit with Heroku.

From this I know how I can set start script: https://devcenter.heroku.com/articles/node-best-practices#specify-a-start-script

And I have it. You can see it here: https://www.dropbox.com/s/y5g6otxtfv5f46r/Screenshot%202015-01-22%2023.58.56.png?dl=0

Do you know where can be the problem? Can you help me, how I can use the site on the real server? Thank you so much! And if you know some better side than Heroku, I will be really glad for the tip.

Thank you again!
Vlastimil

**Comment by BradDenver** [comment]
Sorry @vlafiser I didn't get a chance to look at this yesterday and now won't have a chance until Monday Aus time

**Comment by vlafiser** [comment]
Hi @BradDenver sure, I understand and I will really glad if you will take a look on that at the Monday. ;)
I want use it on my new personal website and I mean can be cool promo for your repo. Of course, I will write you to the credits, because the stack is really fit for me.

Thanks and I'm looking forward for the help with the deploy issue.

**Comment by BradDenver** [comment]
@vlafiser I created a branch https://github.com/BradDenver/react-static-site/tree/deployable that I was able to deploy and run on heroku. To get it to work I had to add a postinstall npm script to run bower install. I also needed to update publicServer.js to use process.env.PORT

**Comment by vlafiser** [comment]
Thank you so much @BradDenver !

But now still not working for me, but I know, now is it my fail. If I "create heroku" and made first push, the page is still with error. Is needed add some script after push? I just read the tutorial on https://scotch.io/tutorials/how-to-deploy-a-node-js-app-to-heroku but maybe is the way little bit different. Can you help me please? :)

**Comment by BradDenver** [comment]
The heroku guide is pretty good https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction

make sure you have pushed the branch to heroku `git push heroku deployable:master`

other than that all I can suggest is having a look at your logs with `heroku logs --tail`

**Comment by vlafiser** [comment]
@BradDenver Thank you man, you are the best! All working right.

**Comment by BradDenver** [comment]
Glad to hear it
