### ISSUE TITLE
Drop bower in favor of NPM?

### ISSUE THREAD

**Issue by bebraw** [BradDenver/react-static-site#7]
Just a quick FYI. You can install pure via NPM. This will eliminate dependency on Bower. Here's a patch for you to try. I'm not sure if it applies directly since I had to stab it by hand (some build is included in the repo...) but you get the idea. If you want I can make a PR.

``` diff
diff --git a/build.js b/build.js
index f9df322..42a4806 100644
--- a/build.js
+++ b/build.js
@@ -16,7 +16,7 @@ webpack(config[1], function(err, stats) {

     var assets = 'public/assets';
     mkdirp.sync(assets);
-    fs.writeFileSync(assets + '/pure.css', fs.readFileSync('bower_components/pure/pure.css'));
+    fs.writeFileSync(assets + '/pure.css', fs.readFileSync('node_modules/purecss/pure.css'));
     fs.writeFileSync(assets + '/style.css', fs.readFileSync('elements/style.css'));

     for(var path in paths.allPaths()) {
diff --git a/dev/entry.jsx b/dev/entry.jsx
index a22be9d..ec922e4 100644
--- a/dev/entry.jsx
+++ b/dev/entry.jsx
@@ -2,7 +2,7 @@ var React = require('react'),
   Router = require('react-router'),
   Routes = require('../elements/Routes.jsx');

-require('../bower_components/pure/pure.css');
+require('purecss/pure.css');
 require('../elements/style.css');

 Router.run(Routes, Router.HistoryLocation,  function (Handler) {
diff --git a/package.json b/package.json
index cafd3e3..321c610 100644
--- a/package.json
+++ b/package.json
@@ -16,6 +16,7 @@
     "markdown-loader": "^0.1.2",
     "mkdirp": "^0.5.0",
     "moment": "^2.9.0",
+    "purecss": "^0.5.0",
     "raw-loader": "^0.5.1",
     "react": "^0.12.2",
     "react-hot-loader": "^1.0.4",
```

**Comment by BradDenver** [comment]
Thank you very much for the feedback Juho.

I am still undecided as to my final css approach so I'll leave it in bower for now. I might also be good to leave it in bower as it shows a general technique that could be used for most other css frameworks (as npm support varies).

When I do my next blog post on react static sites I will mention both techniques and presuming I continue to use Pure I will probably switch to npm.

**Comment by bebraw** [comment]
Ok.

By the way, check out https://github.com/eldh/antwar . It's a friendly fork based on your work. Maybe it would be a good idea to join the efforts (same goal).

**Comment by BradDenver** [comment]
Ah Cool. Thanks for the link. I'll have a look at it.
